# Generated by Django 4.2 on 2024-12-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjob',
            old_name='user',
            new_name='employee',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='applied_at',
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='status',
            field=models.CharField(default='Applied', max_length=50),
        ),
    ]
