# Generated by Django 4.2 on 2024-12-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_employee_appliedjob_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjob',
            name='company_name',
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='status',
            field=models.CharField(default='Applied', max_length=50),
        ),
    ]
