# Generated by Django 4.2 on 2024-12-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_appliedjob_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='interview_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='interview_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
