# Generated by Django 4.2 on 2024-12-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('company', 'Company'), ('employee', 'Employee')], default='employee', max_length=10),
        ),
    ]
